version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password123
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    tty: true
volumes:
  db_data: